/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-22 01:57:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/naver0314/workall/naver0314devops11/springwork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMybatisMember/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/naver0314/workall/naver0314devops11/springwork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMybatisMember/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1715836474464L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Dancing+Script:wght@400..700&family=East+Sea+Dokdo&family=Jua&family=Gaegu&family=Gamja+Flower&family=Pacifico&family=Single+Day&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("   <script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("   <style>\r\n");
      out.write("       body *{\r\n");
      out.write("           font-family: 'Jua';\r\n");
      out.write("       }\r\n");
      out.write("   </style>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("   let jungbok=false;\r\n");
      out.write("   \r\n");
      out.write("   $(function(){\r\n");
      out.write("       $(\"#myfile\").change(function(){\r\n");
      out.write("           //console.log($(this)[0]);//type 이 file 인경우 배열타입으로 넘어온다\r\n");
      out.write("           let reg=/(.*?)\\/(jpg|jpeg|png|gif)$/;\r\n");
      out.write("           let f=$(this)[0].files[0];\r\n");
      out.write("           if(!f.type.match(reg)){\r\n");
      out.write("               alert(\"이미지 파일만 가능합니다\");\r\n");
      out.write("               return;\r\n");
      out.write("           }\r\n");
      out.write("           if(f){\r\n");
      out.write("               let reader=new FileReader();\r\n");
      out.write("               reader.onload=function(e){\r\n");
      out.write("                   $(\"#showimg1\").attr(\"src\",e.target.result);\r\n");
      out.write("               }\r\n");
      out.write("               reader.readAsDataURL($(this)[0].files[0]);\r\n");
      out.write("           }\r\n");
      out.write("       });\r\n");
      out.write("       \r\n");
      out.write("       //중복버튼 이벤트\r\n");
      out.write("       $(\"#btncheckid\").click(function(){\r\n");
      out.write("    	  if($(\"#myid\").val()==''){\r\n");
      out.write("    		  alert(\"가입할 아이디를 입력해주세요\");\r\n");
      out.write("    		  return;\r\n");
      out.write("    	  }\r\n");
      out.write("    	  \r\n");
      out.write("    	  $.ajax({\r\n");
      out.write("    		 type:\"get\",\r\n");
      out.write("    		 dataType:\"json\",\r\n");
      out.write("    		 url:\"./idcheck\",\r\n");
      out.write("    		 data:{\"searchid\":$(\"#myid\").val()},\r\n");
      out.write("    		 success:function(data){\r\n");
      out.write("    			 if(data.count==0){\r\n");
      out.write("    				 alert(\"가입 가능한 아이디입니다\");\r\n");
      out.write("    				 jungbok=true;\r\n");
      out.write("    			 }else{\r\n");
      out.write("    				 alert(\"이미 가입되어있는 아이디입니다\");\r\n");
      out.write("    				 jungbok=false;\r\n");
      out.write("    				 $(\"#myid\").val(\"\");\r\n");
      out.write("    			 }\r\n");
      out.write("    		 }\r\n");
      out.write("    	  });\r\n");
      out.write("       });\r\n");
      out.write("       \r\n");
      out.write("       //아이디를 입력시 다시 중복확인을 누르도록 중복변수를 초기화\r\n");
      out.write("       $(\"#myid\").keyup(function(){\r\n");
      out.write("    	   jungbok=false;\r\n");
      out.write("       });\r\n");
      out.write("   });  //close function \r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("   function check()\r\n");
      out.write("   {\r\n");
      out.write("	   if(!jungbok){\r\n");
      out.write("		   alert(\"아이디 중복확인을 해주세요\");\r\n");
      out.write("		   return false;//false반환시 action 실행을 안함\r\n");
      out.write("	   }	   \r\n");
      out.write("   }\r\n");
      out.write("   </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"./insert\" method=\"post\" enctype=\"multipart/form-data\"\r\n");
      out.write("onsubmit=\"return check()\">\r\n");
      out.write("	<table class=\"table table-bordered\" style=\"width: 400px;\">\r\n");
      out.write("		<caption align=\"top\">\r\n");
      out.write("			<h3><b>회원 가입</b></h3>\r\n");
      out.write("		</caption>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"100\"  class=\"table-info\">이름</th>\r\n");
      out.write("			<td colspan=\"2\">\r\n");
      out.write("				<input type=\"text\" name=\"name\" class=\"form-control\"\r\n");
      out.write("				required=\"required\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"100\"  class=\"table-info\">아이디</th>\r\n");
      out.write("			<td colspan=\"2\">\r\n");
      out.write("			  <div class=\"input-group\">\r\n");
      out.write("				<input type=\"text\" name=\"myid\" id=\"myid\" class=\"form-control\"\r\n");
      out.write("				required=\"required\">\r\n");
      out.write("				&nbsp;\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-sm btn-danger\"\r\n");
      out.write("				id=\"btncheckid\">중복확인</button>\r\n");
      out.write("			  </div>				\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"100\"  class=\"table-info\">사진</th>\r\n");
      out.write("			<td width=\"200\"> \r\n");
      out.write("				<input type=\"file\" name=\"myfile\" id=\"myfile\" class=\"form-control\"\r\n");
      out.write("				required=\"required\" >\r\n");
      out.write("			</td>	\r\n");
      out.write("			<td rowspan=\"2\">\r\n");
      out.write("				<img src=\"\" id=\"showimg1\" style=\"width: 100%;\"\r\n");
      out.write("				onerror=\"this.src='../image/noimage1.png'\">\r\n");
      out.write("			</td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"100\"  class=\"table-info\">비밀번호</th>\r\n");
      out.write("			<td width=\"200\"> \r\n");
      out.write("				<input type=\"password\" name=\"passwd\" class=\"form-control\"\r\n");
      out.write("				required=\"required\" maxlength=\"8\">\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"100\"  class=\"table-info\">핸드폰</th>\r\n");
      out.write("			<td width=\"200\" colspan=\"2\"> \r\n");
      out.write("				<input type=\"tel\" name=\"hp\" class=\"form-control\"\r\n");
      out.write("				required=\"required\" pattern=\"[0-9]{3}-[0-9]{4}-[0-9]{4}\"\r\n");
      out.write("				placeholder=\"xxx-xxxx-xxxx\">\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"100\"  class=\"table-info\">이메일</th>\r\n");
      out.write("			<td width=\"200\" colspan=\"2\"> \r\n");
      out.write("				<input type=\"email\" name=\"email\" class=\"form-control\"\r\n");
      out.write("				required=\"required\">\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"100\"  class=\"table-info\">주소</th>\r\n");
      out.write("			<td width=\"200\" colspan=\"2\"> \r\n");
      out.write("				<input type=\"text\" name=\"addr\" class=\"form-control\"\r\n");
      out.write("				required=\"required\">\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th width=\"100\"  class=\"table-info\">생년월일</th>\r\n");
      out.write("			<td width=\"200\" colspan=\"2\"> \r\n");
      out.write("				<input type=\"date\" name=\"birthday\" class=\"form-control\"\r\n");
      out.write("				value=\"2024-01-01\">\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"3\" align=\"center\">\r\n");
      out.write("				<button type=\"submit\" class=\"btn btn-outline-danger\"\r\n");
      out.write("				style=\"width: 100px;\">회원가입</button>\r\n");
      out.write("				\r\n");
      out.write("				<button type=\"reset\" class=\"btn btn-outline-danger\"\r\n");
      out.write("				style=\"width: 100px;\">초기화</button>\r\n");
      out.write("				\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
